ec2 test

diff --git a/.github/workflows/appsignals-e2e-ec2-test.yml b/.github/workflows/appsignals-e2e-ec2-test.yml
--- a/.github/workflows/appsignals-e2e-ec2-test.yml
+++ b/.github/workflows/appsignals-e2e-ec2-test.yml
@@ -1,183 +1,263 @@
+## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
+## SPDX-License-Identifier: Apache-2.0
+
 # This is a reusable workflow for running the E2E test for App Signals.
 # It is meant to be called from another workflow.
-# This E2E test is responsible for validating setting up a sample application on an EC2 instance and enabling
-# App Signals using the staging .rpm of Cloudwatch Agent. It validates the generated telemetry
-# including logs, metrics, and traces, then cleans up the cluster. The testing resources can be found in the
-# ADOT java instrumentation repo: https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/testing
 # Read more about reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
-name: App Signals Enablement E2E Testing - EC2
+name: App Signals Enablement E2E Testing - EC2 Use Case
 on:
   workflow_call:
+    inputs:
+      aws-region:
+        required: true
+        type: string
+      caller-workflow-name:
+        required: true
+        type: string
 
 permissions:
   id-token: write
   contents: read
 
 env:
-  AWS_DEFAULT_REGION: us-east-1
-  APP_SIGNALS_E2E_TEST_ACCOUNT_ID: ${{ secrets.APP_SIGNALS_E2E_TEST_ACCOUNT_ID }}
-  SAMPLE_APP_FRONTEND_SERVICE_JAR: "s3://sample-app-remote/sample-app.jar"
-  SAMPLE_APP_REMOTE_SERVICE_JAR: "s3://sample-app-remote/sample-app-remote.jar"
-  GET_ADOT_JAR_COMMANBD: "wget -O adot.jar https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar"
-  GET_CW_AGENT_RPM_COMMAND: "aws s3 cp s3://cwagent-rpm/integration-test/amazon-cloudwatch-agent-123-1.rpm ./cw-agent.rpm"
+  # The precense of this env var is required for use by terraform and AWS CLI commands
+  # It is not redundant
+  AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
+  TEST_ACCOUNT: ${{ secrets.APP_SIGNALS_E2E_TEST_ACC }}
+  SAMPLE_APP_FRONTEND_SERVICE_JAR: s3://sample-app-remote/sample-app.jar
+  SAMPLE_APP_REMOTE_SERVICE_JAR: s3://sample-app-remote/sample-app-remote.jar
+  APP_SIGNALS_ADOT_JAR: "https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar"
   METRIC_NAMESPACE: AppSignals
   LOG_GROUP_NAME: /aws/appsignals/generic
+  TEST: ${{ inputs.test }}
+  GET_ADOT_JAR_COMMAND: "wget -O adot.jar https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar"
+  GET_CW_AGENT_RPM_COMMAND: "wget -O cw-agent.rpm https://amazoncloudwatch-agent-${{ inputs.aws-region }}.s3.${{ inputs.aws-region }}.amazonaws.com/amazon_linux/amd64/1.300031.0b313/amazon-cloudwatch-agent.rpm"
+  TEST_RESOURCES_FOLDER: /home/runner/work/aws-application-signals-test-framework/aws-application-signals-test-framework
+
 
 jobs:
   e2e-ec2-test:
     runs-on: ubuntu-latest
     steps:
-      - name: Get testing resources from ADOT
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
-          repository: jj22ee/aws-otel-java-instrumentation
-          ref: main
-
-      - name: Download patch action script
-        uses: actions/checkout@v4
-        with:
-          path: patch-dependencies
-          sparse-checkout: |
-            .github/actions/patch-dependencies/action.yml
-      - name: Replace patch dependency action.yml
-        run: |
-          cp -f ./patch-dependencies/.github/actions/patch-dependencies/action.yml ./.github/actions/patch-dependencies/action.yml
-      - uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: temurin
+          repository: jj22ee/aws-application-signals-test-framework
+          ref: main #7785b97de2adb2bb7c61e47c9ac02c267fb5a151
+          fetch-depth: 0
 
       - name: Generate testing id
         run: echo TESTING_ID="${{ github.run_id }}-${{ github.run_number }}" >> $GITHUB_ENV
 
+      # - name: Configure AWS Credentials
+      #   uses: aws-actions/configure-aws-credentials@v4
+      #   with:
+      #     role-to-assume: ${{ secrets.E2E_SECRET_TEST_ROLE_ARN }}
+      #     aws-region: us-east-1
+
+      # - name: Retrieve account
+      #   uses: aws-actions/aws-secretsmanager-get-secrets@v1
+      #   with:
+      #     secret-ids:
+      #       ACCOUNT_ID, region-account/${{ inputs.aws-region }}
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: ${{ secrets.APP_SIGNALS_E2E_IAM_ROLE }}
-          aws-region: ${{ env.AWS_DEFAULT_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN_JAVA_EKS }}
+          aws-region: ${{ inputs.aws-region }}
 
       - name: Set up terraform
-        uses: hashicorp/setup-terraform@v3
+        uses: ./.github/workflows/actions/execute_and_retry
         with:
-          terraform_wrapper: false
+          command: "wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg"
+          post-command: 'echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list \
+          sudo apt update && sudo apt install terraform'
 
-      - name: Deploy sample app via terraform
-        working-directory: testing/terraform/ec2
+      - name: Initiate Terraform
+        uses: ./.github/workflows/actions/execute_and_retry
+        with:
+          command: "cd ./terraform/ec2 && terraform init && terraform validate"
+          cleanup: "rm -rf .terraform && rm -rf .terraform.lock.hcl"
+
+      - name: Deploy sample app via terraform and wait for endpoint to come online
+        working-directory: terraform/ec2
         run: |
-          terraform init
-          terraform validate
-          terraform apply -auto-approve \
-            -var="aws_region=${{ env.AWS_DEFAULT_REGION }}" \
-            -var="test_id=${{ env.TESTING_ID }}" \
-            -var="sample_app_jar=${{ env.SAMPLE_APP_FRONTEND_SERVICE_JAR }}" \
-            -var="sample_remote_app_jar=${{ env.SAMPLE_APP_REMOTE_SERVICE_JAR }}" \
-            -var="get_cw_agent_rpm_command=${{ env.GET_CW_AGENT_RPM_COMMAND }}" \
-            -var="get_adot_jar_command=${{ env.GET_ADOT_JAR_COMMANBD }}"
+          # Attempt to deploy the sample app on an EC2 instance and wait for its endpoint to come online. 
+          # There may be occasional failures due to transitivity issues, so try up to 2 times. 
+          # deployment_failed of 0 indicates that both the terraform deployment and the endpoint are running, while 1 indicates
+          # that it failed at some point
+          retry_counter=0
+          max_retry=2
+          while [ $retry_counter -lt $max_retry ]; do
+            echo "Attempt $retry_counter"
+            deployment_failed=0
+            terraform apply -auto-approve \
+              -var="aws_region=${{ inputs.aws-region }}" \
+              -var="test_id=${{ env.TESTING_ID }}" \
+              -var="sample_app_jar=${{ env.SAMPLE_APP_FRONTEND_SERVICE_JAR }}" \
+              -var="sample_remote_app_jar=${{ env.SAMPLE_APP_REMOTE_SERVICE_JAR }}" \
+              -var="get_cw_agent_rpm_command=${{ env.GET_CW_AGENT_RPM_COMMAND }}" \
+              -var="get_adot_jar_command=${{ env.GET_ADOT_JAR_COMMAND }}" \
+            || deployment_failed=$?
+          
+            if [ $deployment_failed -eq 1 ]; then
+              echo "Terraform deployment was unsuccessful. Will attempt to retry deployment."
+            fi
+          
+            # If the deployment_failed is still 0, then the terraform deployment succeeded and now try to connect to the endpoint.
+            # Attempts to connect will be made for up to 10 minutes
+            if [ $deployment_failed -eq 0 ]; then
+              echo "Attempting to connect to the endpoint"
+              main_sample_app_endpoint=http://$(terraform output sample_app_main_service_public_dns):8080
+              attempt_counter=0
+              max_attempts=30
+              until $(curl --output /dev/null --silent --head --fail $(echo "$main_sample_app_endpoint" | tr -d '"')); do
+                if [ ${attempt_counter} -eq ${max_attempts} ];then
+                  echo "Failed to connect to endpoint. Will attempt to redeploy sample app."
+                  deployment_failed=1
+                  break
+                fi
+          
+                printf '.'
+                attempt_counter=$(($attempt_counter+1))
+                sleep 10
+              done
+          
+              echo "Attempting to connect to the remote sample app endpoint"
+              remote_sample_app_endpoint=http://$(terraform output sample_app_remote_service_public_ip):8080/healthcheck
+              attempt_counter=0
+              max_attempts=30
+              until $(curl --output /dev/null --silent --head --fail $(echo "$remote_sample_app_endpoint" | tr -d '"')); do
+                if [ ${attempt_counter} -eq ${max_attempts} ];then
+                  echo "Failed to connect to endpoint. Will attempt to redeploy sample app."
+                  deployment_failed=1
+                  break
+                fi
+          
+                printf '.'
+                attempt_counter=$(($attempt_counter+1))
+                sleep 10
+              done
+            fi
+          
+            # If the success is 1 then either the terraform deployment or the endpoint connection failed, so first destroy the
+            # resources created from terraform and try again.
+            if [ $deployment_failed -eq 1 ]; then
+              echo "Destroying terraform"
+              terraform destroy -auto-approve \
+                -var="test_id=${{ env.TESTING_ID }}" 
+          
+              retry_counter=$(($retry_counter+1))
+            else
+              # If deployment succeeded, then exit the loop
+              break
+            fi
+          
+            if [ $retry_counter -eq $max_retry ]; then
+              echo "Max retry reached, failed to deploy terraform and connect to the endpoint. Exiting code"
+              exit 1
+            fi
+          done
+
       - name: Get the ec2 instance ami id
-        working-directory: testing/terraform/ec2
         run: |
           echo "EC2_INSTANCE_AMI=$(terraform output ec2_instance_ami)" >> $GITHUB_ENV
+        working-directory: terraform/ec2
+
       - name: Get the sample app endpoint
-        working-directory: testing/terraform/ec2
         run: |
           echo "MAIN_SERVICE_ENDPOINT=$(terraform output sample_app_main_service_public_dns):8080" >> $GITHUB_ENV
           echo "REMOTE_SERVICE_IP=$(terraform output sample_app_remote_service_public_ip)" >> $GITHUB_ENV
-      
+        working-directory: terraform/ec2
 
-      - name: Wait for app endpoint to come online
-        id: endpoint-check
-        run: |
-          attempt_counter=0
-          max_attempts=30
-          until $(curl --output /dev/null --head --fail http://${{ env.MAIN_SERVICE_ENDPOINT }}); do
-            if [ ${attempt_counter} -eq ${max_attempts} ];then
-              echo "Max attempts reached"
-              exit 1
-            fi
-            printf '.'
-            attempt_counter=$(($attempt_counter+1))
-            sleep 10
-          done
       # This steps increases the speed of the validation by creating the telemetry data in advance
       - name: Call all test APIs
         continue-on-error: true
         run: |
-          curl -S -s -o /dev/null http://${{ env.MAIN_SERVICE_ENDPOINT }}/outgoing-http-call/
-          curl -S -s -o /dev/null http://${{ env.MAIN_SERVICE_ENDPOINT }}/aws-sdk-call/
-          curl -S -s -o /dev/null http://${{ env.MAIN_SERVICE_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_IP }}/
-          curl -S -s -o /dev/null http://${{ env.MAIN_SERVICE_ENDPOINT }}/client-call/
+          curl -S -s http://${{ env.MAIN_SERVICE_ENDPOINT }}/outgoing-http-call
+          curl -S -s http://${{ env.MAIN_SERVICE_ENDPOINT }}/aws-sdk-call
+          curl -S -s http://${{ env.MAIN_SERVICE_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_IP }}
+          curl -S -s http://${{ env.MAIN_SERVICE_ENDPOINT }}/client-call
           
-      # cache local patch outputs
-      - name: Cache local Maven repository
-        id: cache-local-maven-repo
-        uses: actions/cache@v3
+      - name: Build Gradlew
+        uses: ./.github/workflows/actions/execute_and_retry
         with:
-          path: |
-            ~/.m2/repository/io/opentelemetry/
-          key: ${{ runner.os }}-maven-local-${{ hashFiles('.github/patches/opentelemetry-java*.patch') }}
-
-      - name: Publish patched dependencies to maven local
-        uses: ./.github/actions/patch-dependencies
-        if: steps.cache-local-maven-repo.outputs.cache-hit != 'true'
+          max_retry: 4
+          command: "./gradlew"
 
       # Validation for pulse telemetry data
-      - name: Validate generated EMF logs
-        id: log-validation
-        run: ./gradlew testing:validator:run --args='-c ec2/log-validation.yml
-          --testing-id ${{ env.TESTING_ID }}
-          --endpoint http://${{ env.MAIN_SERVICE_ENDPOINT }}
-          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_IP }}:8080
-          --region ${{ env.AWS_DEFAULT_REGION }}
-          --account-id ${{ env.APP_SIGNALS_E2E_TEST_ACCOUNT_ID }}
-          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-          --log-group ${{ env.LOG_GROUP_NAME }}
-          --service-name sample-application-${{ env.TESTING_ID }}
-          --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
-          --request-body ip=${{ env.REMOTE_SERVICE_IP }}
-          --instance-ami ${{ env.EC2_INSTANCE_AMI }}
-          --rollup'
+      # - name: Validate generated EMF logs
+      #   id: log-validation
+      #   run: ./gradlew validator:run --args='-c ec2/log-validation.yml
+      #     --testing-id ${{ env.TESTING_ID }}
+      #     --endpoint http://${{ env.MAIN_SERVICE_ENDPOINT }}
+      #     --remote-service-deployment-name ${{ env.REMOTE_SERVICE_IP }}:8080
+      #     --region ${{ inputs.aws-region }}
+      #     --account-id ${{ secrets.ACCOUNT_ID }}
+      #     --metric-namespace ${{ env.METRIC_NAMESPACE }}
+      #     --log-group ${{ env.LOG_GROUP_NAME }}
+      #     --service-name sample-application-${{ env.TESTING_ID }}
+      #     --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
+      #     --request-body ip=${{ env.REMOTE_SERVICE_IP }}
+      #     --instance-ami ${{ env.EC2_INSTANCE_AMI }}
+      #     --rollup'
 
       - name: Validate generated metrics
         id: metric-validation
         if: (success() || steps.log-validation.outcome == 'failure') && !cancelled()
-        run: ./gradlew testing:validator:run --args='-c ec2/metric-validation.yml
+        run: ./gradlew validator:run --args='-c ec2/metric-validation.yml
           --testing-id ${{ env.TESTING_ID }}
           --endpoint http://${{ env.MAIN_SERVICE_ENDPOINT }}
           --remote-service-deployment-name ${{ env.REMOTE_SERVICE_IP }}:8080
-          --region ${{ env.AWS_DEFAULT_REGION }}
-          --account-id ${{ env.APP_SIGNALS_E2E_TEST_ACCOUNT_ID }}
+          --region ${{ inputs.aws-region }}
+          --account-id ${{ secrets.ACCOUNT_ID }}
           --metric-namespace ${{ env.METRIC_NAMESPACE }}
           --log-group ${{ env.LOG_GROUP_NAME }}
           --service-name sample-application-${{ env.TESTING_ID }}
           --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
-          --request-body ip=${{ env.REMOTE_SERVICE_IP }}
+          --request-body ip=${{ env.REMOTE_SERVICE_IP }}&id=${{ env.TESTING_ID }}
           --instance-ami ${{ env.EC2_INSTANCE_AMI }}
           --rollup'
 
-      - name: Validate generated traces
-        id: trace-validation
-        if: (success() || steps.log-validation.outcome == 'failure' || steps.metric-validation.outcome == 'failure') && !cancelled()
-        run: ./gradlew testing:validator:run --args='-c ec2/trace-validation.yml
-          --testing-id ${{ env.TESTING_ID }}
-          --endpoint http://${{ env.MAIN_SERVICE_ENDPOINT }}
-          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_IP }}:8080
-          --region ${{ env.AWS_DEFAULT_REGION }}
-          --account-id ${{ env.APP_SIGNALS_E2E_TEST_ACCOUNT_ID }}
-          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-          --log-group ${{ env.LOG_GROUP_NAME }}
-          --service-name sample-application-${{ env.TESTING_ID }}
-          --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
-          --request-body ip=${{ env.REMOTE_SERVICE_IP }}
-          --instance-ami ${{ env.EC2_INSTANCE_AMI }}
-          --rollup'
+      # - name: Validate generated traces
+      #   id: trace-validation
+      #   if: (success() || steps.log-validation.outcome == 'failure' || steps.metric-validation.outcome == 'failure') && !cancelled()
+      #   run: ./gradlew validator:run --args='-c ec2/trace-validation.yml
+      #     --testing-id ${{ env.TESTING_ID }}
+      #     --endpoint http://${{ env.MAIN_SERVICE_ENDPOINT }}
+      #     --remote-service-deployment-name ${{ env.REMOTE_SERVICE_IP }}:8080
+      #     --region ${{ inputs.aws-region }}
+      #     --account-id ${{ secrets.ACCOUNT_ID }}
+      #     --metric-namespace ${{ env.METRIC_NAMESPACE }}
+      #     --log-group ${{ env.LOG_GROUP_NAME }}
+      #     --service-name sample-application-${{ env.TESTING_ID }}
+      #     --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
+      #     --request-body ip=${{ env.REMOTE_SERVICE_IP }}
+      #     --instance-ami ${{ env.EC2_INSTANCE_AMI }}
+      #     --rollup'
+
+      # - name: Publish metric on test result
+      #   if: always()
+      #   run: |
+      #     if [[ "${{ steps.log-validation.outcome }}" == "success" && "${{ steps.metric-validation.outcome }}" == "success" && "${{ steps.trace-validation.outcome }}" == "success" ]]; then
+      #       aws cloudwatch put-metric-data --namespace 'ADOT/GitHubActions' \
+      #       --metric-name Failure \
+      #       --dimensions repository=${{ github.repository }},branch=${{ github.ref_name }},workflow=${{ inputs.caller-workflow-name }} \
+      #       --value 0.0 \
+      #       --region ${{ inputs.aws-region }}
+      #     else
+      #       aws cloudwatch put-metric-data --namespace 'ADOT/GitHubActions' \
+      #       --metric-name Failure \
+      #       --dimensions repository=${{ github.repository }},branch=${{ github.ref_name }},workflow=${{ inputs.caller-workflow-name }} \
+      #       --value 1.0 \
+      #       --region ${{ inputs.aws-region }}
+      #     fi
 
       # Clean up Procedures
-
       - name: Terraform destroy
         if: always()
         continue-on-error: true
-        working-directory: testing/terraform/ec2
+        working-directory: terraform/ec2
         run: |
           terraform destroy -auto-approve \
             -var="test_id=${{ env.TESTING_ID }}"
-          
